/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MGUud8eUhxV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

"use client";
import { useState } from "react";
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import Image from "next/image"
import seedling from '../app/assets/seedling.jpg'
import event from '../app/assets/event.jpg'
import two from '../app/assets/257.jpeg'
import { mailingListSignup } from '../app/api/actions';

// import { Libre_Franklin } from 'next/font/google'

// Libre_Franklin({
//   subsets: ['latin'],
//   display: 'swap',
// })

const LandingPage = () => {
  const [sendButton, setSendButton] = useState("Join!");
  const [userEmail, setUserEmail] = useState("");

  const joinMailingList = async (e) => {
    console.log('userEmail', userEmail)
    e.preventDefault()
    setSendButton("Joining...");
    await mailingListSignup({
      email: userEmail,
    });
    setSendButton("Joined!");
  }
  return (<>
    <section
      className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-[#FF6B6B] text-white">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-6">
            <div className="space-y-4">
              <h1 className="text-5xl font-bold tracking-tighter sm:text-6xl xl:text-7xl">Stay in the Loop</h1>
              <p className="max-w-[600px] text-lg">
                Sign up for our email newsletter and be the first to know about our latest updates, exclusive offers,
                and upcoming events.
              </p>
            </div>
            <div className="w-full max-w-sm space-y-2">
              <form className="flex space-x-2">
                <Input
                  className="max-w-lg flex-1 bg-white text-gray-900 placeholder:text-gray-500"
                  placeholder="Enter your email"
                  type="email"
                  onChange={(e) => setUserEmail(e.target.value)} />
                <Button className="bg-[#4CAF50] hover:bg-[#3e8e41] text-white" onClick={(e) => joinMailingList(e)}>
                  {sendButton}
                </Button>
              </form>
              <p className="text-sm">
                We'll never share your email.
              </p>
            </div>
          </div>
          <div className="flex justify-center">
          <Image
            src={seedling}
            alt="small business support new zealand. image made by ai."
            priority={true}
            className="rounded-lg"
          ></Image>
          </div>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-[#FFF5D1]">
      <div className="container px-4 md:px-6">
        <div
          className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
          <div className="flex flex-col justify-center">
            <div className="space-y-6">
              <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl">An Authentic Community</h2>
              <p
                className="max-w-[600px] text-gray-700 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                What does good business look like? We're building a community for small business owners, entrepreneurs and wantrepreneurs, where real conversations can happen about how small business can respond to the times we're in now. 
              </p>
              <p
                className="max-w-[600px] text-gray-700 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Join a fully supportive, no-bullshit environment where we can share stories, tackle the big challenges and pull the community back together.  
              </p>
              </div>
              <div className="mt-10">
              <div
                className="inline-block rounded-lg bg-[#FFD700] px-3 py-1 text-sm text-gray-900">Featured</div>
              <h3 className="mt-6 text-2xl font-bold tracking-tighter sm:text-3xl">Join Our Latest Event</h3>
              <p
                className="mt-6 max-w-[600px] text-gray-700 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our first event is <b>Compost: How do you know when to throw in the trowel?</b> That's right, we're exploring death and business with people who've been there and people who are thinking about it. The event will be in-person in Wellington and streamed online. Sign up below to get notified when we've fixed a date.  
              </p>
            </div>
            <div className="mt-6 flex flex-col gap-4 min-[400px]:flex-row">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#FF6B6B] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#e65353] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FF6B6B] disabled:pointer-events-none disabled:opacity-50"
                href="#">
                Get Notified
              </Link>
              {/* <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-[#FF6B6B] bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-[#FF6B6B] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FF6B6B] disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800"
                href="#">
                Get Notified
              </Link> */}
            </div>
          </div>
          <div className="flex justify-center">
          <Image
            src={event}
            alt="small business help and funding new zealand. image made by ai."
            priority={true}
            className="rounded-lg"
          ></Image>
          </div>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-[#F0F0F0]">
      <div
        className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Our Cheerleaders</h2>
          <p
            className="mx-auto max-w-[700px] text-gray-700 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Our community champions, heroes and frontline supporters.
          </p>
        </div>
        <div
          className="grid w-full grid-cols-2 lg:grid-cols-5 items-center justify-center gap-8 lg:gap-12 [&>img]:mx-auto">
          <Image
            src={two}
            alt="twofiftyseven willis helps small business networks in wellington thrive."
            priority={true}
            className="rounded-lg"
            width="140"
          ></Image>
        </div>
      </div>
    </section>
    <footer
      className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-[#FF6B6B] text-white">
      <p className="text-xs">© 2024 Compost Inc. All rights reserved.</p>
      <nav className="sm:ml-auto flex gap-4 sm:gap-6">
        {/* <Link className="text-xs hover:underline underline-offset-4" href="#">
          Terms of Service
        </Link>
        <Link className="text-xs hover:underline underline-offset-4" href="#">
          Privacy
        </Link> */}
      </nav>
    </footer>
  </>);
}
 export default LandingPage